POST http://localhost:8080/utilisateur/add
Content-Type: application/json

{
  "nomUtilisateur" : "gzllAZaa",
  "motDePasse" : "gzERa"
}
###
GET http://localhost:8080/utilisateur/all
###
GET http://localhost:8080/utilisateur/nom/AZ
###
POST http://localhost:8080/utilisateur/add
Content-Type: application/json

{
  "nomUtilisateur" : "AAAzezeS",
  "motDePasse" : "DF"
}
###
POST http://localhost:8080/taches/add
Content-Type: application/json

{
  "id" : 1,
  "titre" : "Projet",
  "description" : "MongoDB",
  "dateEcheance" : "2023-06-04",
  "estTerminee" : false,
  "idUtilisateur" : 1
}
###
GET http://localhost:8080/taches/1/all
###
GET http://localhost:8080/taches/count/Souhail